#!/usr/bin/env bash

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
	echo -e "\033[1mfia\033[0m: Find In All, a interactive fuzzy finder for all kinds of files,"
	echo -e "     using ripgrep-all, fzf, bat and your editor of choice."
	echo ""
	echo -e "Usage: \033[1mfia\033[0m [options] <query>"
	echo ""
	echo "Options:"
	echo -e "  \033[1m-c, --code\033[0m    Open in VS Code"
	echo -e "  \033[1m-s, --subl\033[0m    Open in Sublime Text"
	echo -e "  \033[1m-e, --editor\033[0m  Open in \$EDITOR"
  echo ""
  echo "By default, fia will copy the file name and line number to the clipboard."
	exit 1
fi

query=""
for param in "$@"; do
  if [[ $param != -* ]]; then
    query="$param"
    break
  fi
done

result=$(
  rga \
    --ignore-case \
    --color=always \
    --line-number \
    --no-heading "$query" \
  | fzf \
    --ansi \
    --delimiter ':' \
    --preview "bat --color=always {1} --highlight-line {2}" \
    --preview-window 'right,60%,border-left,+{2}+3/3,~3' \
)

file="${result%%:*}"
linenumber=$(echo "${result}" | cut -d: -f2)

for p in "$@"; do
	if [ "$p" == "--code" ] || [ "$p" == "-c" ]; then
		fn="code -g \"$file:$linenumber\""
		break
	elif [ "$p" == "--subl" ] || [ "$p" == "-s" ]; then
		fn="subl \"$file:$linenumber\""
		break
	elif [ "$p" == "--editor" ] || [ "$p" == "-e" ]; then
		fn="$EDITOR \"$file:$linenumber\""
		break
	else
		fn="echo \"$file:$linenumber\" | pbcopy"
	fi
done

if [ -n "$file" ]; then
  echo "$file:$linenumber"
	eval "$fn"
fi

