#!/usr/bin/env python3

# Will convert strings like "Fix bug about foo and bar #123"
# to "123-fix-bug-about-foo-and-bar"

import re
from os import system
from sys import platform

# Get user input
s = input("Enter issue header, e.g. 'Fix bug about foo and bar #352':\n> ")
s = s.strip()

# Find issue number (123)
d = re.findall(r"(?<=\#)[0-9]+$",s)[-1]

# Get description part of string (Fix bug about foo and bar)
p = re.compile(r"[\W]*#[0-9]+$")
s = p.sub("", s)

# "Fix 'bug' about foo/bar" -> fix-bug-about-foo-bar
s = s.lower()

substitutions = [
	[" ", "-"], 
	["/", "-"], 
	["\"", ""], 
	["'", ""],
	["\\", ""],
	[",", ""],
	[":", ""],
	["?", ""],
]
for pair in substitutions:
	s = s.replace(pair[0], pair[1])

# Combine number and description
s = f"{d}-{s}"

# Remove duplicate dashes "fix---bug" -> "fix-bug"
dash = re.compile(r"[-]{2,}")
s = dash.sub("-", s)

# Add user ID
s = f"rosvik/{s}"

if platform.find('darwin') > -1:
	# Copy to clipboard on MacOS
	system(f'echo "{s}" | pbcopy')

print(s)
